apiVersion: v1
kind: Service
metadata:
  name: desafio-devops-app-service
spec:
  selector:
    app: desafio-devops-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
